### ISSUE TITLE
App requires Gradio 6 but requirements allow Gradio 5, where it crashes on startup

### ISSUE THREAD

**Issue by alvarezhluis** [BenjaminEinhorn/RAG_StudyAssistant#13]
## What happens
requirements.txt and pyproject.toml both specify `gradio>=5.0,<7`. A fresh install that resolves to Gradio 5 cannot start the app at all.

`demo.launch(theme=theme, share=False)` is Gradio 6 syntax. In Gradio 5, `theme` belongs on `gr.Blocks(...)`, so launch() rejects it. Gradio moved theme, css, js and head from Blocks to launch() in version 6.

## Steps to reproduce
1. In an existing venv: `pip install "gradio<6"` then `pip install -e ".[dev]"`
2. `python -m course_assistant.ui.app`

## Expected
Either the app starts, or the dependency range states the version it actually needs.

## Actual
Traceback (most recent call last):
  File ".../src/course_assistant/ui/app.py", line 271, in <module>
    main()
  File ".../src/course_assistant/ui/app.py", line 267, in main
    demo.launch(theme=theme, share=False)
TypeError: Blocks.launch() got an unexpected keyword argument 'theme'

## Suggested fix
Change the requirement to `gradio>=6,<7` in both requirements.txt and pyproject.toml. (Alternatively, make the theme call version-aware, but pinning is simpler and matches what the team already runs.)

## Why it matters
Anyone installing from a fresh clone, including the grader, can land on Gradio 5 and get an app that does not start.

## Environment
macOS, Python 3.12.14. Fails on gradio 5.50.0; works on gradio 6.28.0.
